### ISSUE TITLE
Report for the app

### ISSUE THREAD

**Issue by SupToSecret** [byZeroOfficial/KGH-Vertretungsplan-App#5]
window with description is kinda small

**Comment by SupToSecret** [comment]
also text is kinda small, but app is good (i won't use it anyways, cuz i'm RuSsIaN and i don't speak german)

**Comment by SupToSecret** [comment]
MAKE A RUSSIAN VERSION (and english maybe(but russian is more important))

**Comment by ghost** [comment]
> MAKE A RUSSIAN VERSION (and english maybe(but russian is more important))

But why do you need a russian version if you don't visit the school this app was made for?

**Comment by EinfachRuwen** [comment]
Because i told her about the app and she rated it in design ;)

**Comment by EinfachRuwen** [comment]
but i'll think about it

**Comment by SupToSecret** [comment]
yes

**Comment by EinfachRuwen** [comment]
I made a full translation of the app in english, hope thats enough. you may open this issue again, if you want to say anything :)
