### ISSUE TITLE
GitHub-Icon

### ISSUE THREAD

**Issue by ghost** [byZeroOfficial/KGH-Vertretungsplan-App#6]
**Beschreibe den Bug**
Das GitHub-Icon ist ein bisschen broken.

**Screenshots**
![Screenshot_2021-02-23-15-14-46-54_b336ae3ddfa08d75b325192cadea8a42.jpg](https://user-images.githubusercontent.com/67111271/108856092-fac55c00-75e9-11eb-92d0-cb9128fb9292.jpg)

**Informationen zum Endgerät**
 - Android 10
 - Realme 6 Pro
- Version 2.1.3.2 FIXED!!!

**Weitere Informationen**
404-Informationen not found

**Comment by EinfachRuwen** [comment]
Haha :D, das ist so :)
![Guck](https://img.icons8.com/cute-clipart/512/000000/github.png)
Du kannst dir aber eins von icons8.com aussuchen, ich schaue dann mal und ersetze es vielleicht.

**Comment by ghost** [comment]
> Haha :D, das ist so :)

Achso, ich dachte dass das ein Bug wäre.

**Comment by EinfachRuwen** [comment]
> Version 2.1.3.2 FIXED!!!
🤣

**Comment by EinfachRuwen** [comment]
Du kannst gerne aber für ein anderes abstimmen

**Comment by EinfachRuwen** [comment]
Hab da wirklich kein gutes gefunden, findest du eins von Icons8 in weiß, super.

**Comment by ghost** [comment]
Ich würde [das hier](https://icons8.com/icon/106564/github) vorschlagen. Ist dem originalem Logo ähnlicher.

**Comment by ghost** [comment]
> Hab da wirklich kein gutes gefunden, findest du eins von Icons8 in weiß, super.

Kannst du nicht einfach die Farben invertieren?

**Comment by EinfachRuwen** [comment]
So? https://cloud.0network.de/private/so-jcw.html

**Comment by EinfachRuwen** [comment]
Ehm eigentlich sollte das weiß sein

**Comment by ghost** [comment]
> > Hab da wirklich kein gutes gefunden, findest du eins von Icons8 in weiß, super.
> 
> Kannst du nicht einfach die Farben invertieren?

@byZeroOfficial

**Comment by EinfachRuwen** [comment]
Kann man die Webseite machen, alles gut. SO? https://cloud.0network.de/private/so-jcw.html

**Comment by EinfachRuwen** [comment]
Das schwarz ist nur zum darstellen

**Comment by ghost** [comment]
> Kann man die Webseite machen, alles gut. SO? https://cloud.0network.de/private/so-jcw.html

YES

**Comment by EinfachRuwen** [comment]
Gut... Nehme das dann mal auf...

**Comment by EinfachRuwen** [comment]
Ich lasse das hier bis zum Fix offen

**Comment by EinfachRuwen** [comment]
![Screenshot](https://user-images.githubusercontent.com/76685126/108914384-88756b80-762b-11eb-9c21-893dbcf4c74c.jpg)
Hmm...

**Comment by EinfachRuwen** [comment]
Der Fix wird in der neuen Version sein, solltest du noch Fragen haben, kannst du das Issue ja wieder öffnen.
