### ISSUE TITLE
Vertretungsplan ist nur weiß

### ISSUE THREAD

**Issue by therealmistericraft** [byZeroOfficial/KGH-Vertretungsplan-App#8]
**Beschreibe den Bug**
Nachdem ich die App geöffnet habe, war die Seite nur weiß. Alle Bedienelemente haben wie zuvor funktioniert.

**Informationen zum Endgerät**
 - Android-Version: 10
 - Smartphone: Huawei P30 lite
 - Version der App: unknown

**Weitere Informationen**
Das KGH hat sein System geändert, vermutlich hängt das Problem damit zusammen.

**Comment by EinfachRuwen** [comment]
Hey!
Nachdem ich kurz nachschaut habe ist die HTML-Version der Vertretungspläne auf der KGH-Website nicht verfügbar. Das erklärt, warum das PHP-Skript die Vertretungspläne nicht downloaden kann.

Von was für einer Systemänderung sprichst du, was wurde geändert? Ist wahrscheinlich wichtig für mich.

LG
byZero

**Comment by EinfachRuwen** [comment]
@therealmistericraft

**Comment by EinfachRuwen** [comment]
@therealmistericraft Ist das hier immer noch ein Problem?

**Comment by therealmistericraft** [comment]
NeinOn 10 Oct 2021 10:28, byZeroOfficial ***@***.***> wrote:
@therealmistericraft Ist das hier immer noch ein Problem?
